# Align
vel_x = 0.1 # 线速度
vel_omega = 0.25 # 角速度
jump_after_align = false # 对齐台阶后是否执行跳跃动作
auto_start = false # 是否自动启动
is_stair_mode = true

# Perception
radius = 0.04 # 离散点半径
min_neighbors = 5 # 近邻点最小数量
orientation_dead_zone = 2 # 角度调整时的死区
orientation_correction = 0 # 角度调整时对两侧tof点数量的修正
orientation_filter = false # 角度调整时两侧点的数量是否采用均值滤波
filter_size = 10 # 均值滤波的步长
blind_forward_threshold = 25 # 停止盲向行走时点数量的阈值

[[approach_threshold]]
z_range = [0.0, 0.10]
threshold = 100 # 停止靠近台阶时点数量的阈值

[[approach_threshold]]
z_range = [0.10, 0.13]
threshold = 80 # 停止靠近台阶时点数量的阈值

[[approach_threshold]]
z_range = [0.13, 0.5]
threshold = 60 # 停止靠近台阶时点数量的阈值
