# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cyberdog_app_pb2 as cyberdog__app__pb2


class GrpcAppStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendMsg = channel.unary_stream(
                '/grpcapi.GrpcApp/sendMsg',
                request_serializer=cyberdog__app__pb2.SendRequest.SerializeToString,
                response_deserializer=cyberdog__app__pb2.RecResponse.FromString,
                )
        self.heartbeat = channel.unary_unary(
                '/grpcapi.GrpcApp/heartbeat',
                request_serializer=cyberdog__app__pb2.Ticks.SerializeToString,
                response_deserializer=cyberdog__app__pb2.Result.FromString,
                )
        self.getFile = channel.unary_stream(
                '/grpcapi.GrpcApp/getFile',
                request_serializer=cyberdog__app__pb2.SendRequest.SerializeToString,
                response_deserializer=cyberdog__app__pb2.FileChunk.FromString,
                )


class GrpcAppServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sendMsg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrpcAppServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendMsg': grpc.unary_stream_rpc_method_handler(
                    servicer.sendMsg,
                    request_deserializer=cyberdog__app__pb2.SendRequest.FromString,
                    response_serializer=cyberdog__app__pb2.RecResponse.SerializeToString,
            ),
            'heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.heartbeat,
                    request_deserializer=cyberdog__app__pb2.Ticks.FromString,
                    response_serializer=cyberdog__app__pb2.Result.SerializeToString,
            ),
            'getFile': grpc.unary_stream_rpc_method_handler(
                    servicer.getFile,
                    request_deserializer=cyberdog__app__pb2.SendRequest.FromString,
                    response_serializer=cyberdog__app__pb2.FileChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpcapi.GrpcApp', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GrpcApp(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sendMsg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpcapi.GrpcApp/sendMsg',
            cyberdog__app__pb2.SendRequest.SerializeToString,
            cyberdog__app__pb2.RecResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpcapi.GrpcApp/heartbeat',
            cyberdog__app__pb2.Ticks.SerializeToString,
            cyberdog__app__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpcapi.GrpcApp/getFile',
            cyberdog__app__pb2.SendRequest.SerializeToString,
            cyberdog__app__pb2.FileChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
