default_color = 0 # 0 white, 1 black
start_direction = 0 # 0 front, 1 back
gradual_duration = 50 # milsecs
stand_gradual_duration_ = 3500 # milsecs
twink_gradual_duration_ = 3500 # milsecs
random_gradual_duration_ = 3500 # milsecs