# 相对量位控姿态站立
cmd_type = 0 
vel_des = [0.0, 0.0, 0.0]
rpy_des = [0.0, 0.0, 0.0]
pos_des = [0.0, 0.0, 0.0]
acc_des = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
ctrl_point = [0.0, 0.0, 0.0]
foot_pose = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
step_height = [0.0, 0.0]
duration = 1000