[[task]]
TaskName = "UwbTracking"
Id = 11
OutDoor = false
DepsNav2LifecycleNodes = []
DepsLifecycleNodes = ["camera/camera_align", "mivinsfollowing", "mcr_uwb", "controller_server_tracking",
"planner_server_tracking", "recoveries_server", "bt_navigator_tracking"]
