[[task]]
TaskName = "UwbTracking"
Id = 11
OutDoor = false
DepsNav2LifecycleNodes = []
DepsLifecycleNodes = ["camera/camera_align", "mivinsfollowing", "mcr_uwb", "controller_server_tracking",
"planner_server_tracking", "recoveries_server", "bt_navigator_tracking"]

[[task]]
TaskName = "LaserMapping"
Id = 5
OutDoor = false
DepsNav2LifecycleNodes = []
DepsLifecycleNodes = ["camera/camera", "map_builder"]

[[task]]
TaskName = "LaserLocalization"
Id = 7
OutDoor = false
DepsNav2LifecycleNodes = []
DepsLifecycleNodes = ["camera/camera_align", "localization_node"]

[[task]]
TaskName = "VisionMapping"
Id = 5
OutDoor = true
DepsNav2LifecycleNodes = []
DepsLifecycleNodes = ["camera/camera", "stereo_camera", "mivinsmapping"]

[[task]]
TaskName = "VisionLocalization"
Id = 7
OutDoor = true
DepsNav2LifecycleNodes = []
DepsLifecycleNodes = ["camera/camera_align", "stereo_camera", "mivinslocalization"]

[[task]]
TaskName = "NavAB"
Id = 1
OutDoor = false
DepsNav2LifecycleNodes = []
DepsLifecycleNodes = ["controller_server_ab", "planner_server_ab", "recoveries_server" , "bt_navigator_ab"]

[[task]]
TaskName = "VisionTracking"
Id = 13
OutDoor = false
DepsNav2LifecycleNodes = [""]
DepsLifecycleNodes = ["camera/camera_align","mivinsfollowing", "tracking", "controller_server_tracking",
"planner_server_tracking", "recoveries_server", "bt_navigator_tracking", "vision_manager"]

[[task]]
TaskName = "ResetNav"
Id = 0
OutDoor = false
DepsNav2LifecycleNodes = []
DepsLifecycleNodes = []


[[task]]
TaskName = "AutoDock"
Id = 9
OutDoor = false
DepsNav2LifecycleNodes = [""]
DepsLifecycleNodes = ["camera/camera_align", "charging_localization", "mivinsfollowing", "controller_server_docking", "planner_server_docking", "recoveries_server", "bt_navigator_docking"]
